);
    });

    it('should handle edge case for odd vertex with node id ending with minus', function () {
      const res = flow.parser.parse('graph TD;A_node-->odd->Vertex Text];');
      const vert = flow.parser.yy.getVertices();

      expect(vert.get('odd-').type).toBe('odd');
      expect(vert.get('odd-').text).toBe('Vertex Text');
    });
    it('should allow forward slashes in lean_right vertices', function () {
      const rest = flow.parser.parse(