', function () {
    expect(() => flow.parser.parse('graph\nX(- My Text (')).toThrowError();
  });

  it('should handle text in diamond vertices with space', function () {
    const res = flow.parser.parse('graph TD;A(chimpansen hoppar)-->C;');

    const vert = flow.parser.yy.getVertices();
    const edges = flow.parser.yy.getEdges();

    expect(vert.get('A').type).toBe('round');
    expect(vert.get('A').text).toBe('chimpansen hoppar');
  });

  it('should handle text in with ?', function () {
    const res = flow.parser.parse('graph TD;A(?)-->|?|C;');

    const vert = flow.parser.yy.getVertices();
    const edges = flow.parser.yy.getEdges();

    expect(vert.get('A').text).toBe('?');
    expect(edges[0].text).toBe('?');
  });
  it('should handle text in with éèêàçô', function () {
    const res = flow.parser.parse('graph TD;A(éèêàçô)-->|éèêàçô|C;');

    const vert = flow.parser.yy.getVertices();
    const edges = flow.parser.yy.getEdges();

    expect(vert.get('A').text).toBe('éèêàçô');
    expect(edges[0].text).toBe('éèêàçô');
  });

  it('should handle text in with ,.?!+-*', function () {
    const res = flow.parser.parse('graph TD;A(,.?!+-*)-->|,.?!+-*|C;');

    const vert = flow.parser.yy.getVertices();
    const edges = flow.parser.yy.getEdges();

    expect(vert.get('A').text).toBe(',.?!+-*');
    expect(edges[0].text).toBe(',.?!+-*');
  });

  it('should throw error at nested set of brackets', function () {
    const str = 'graph TD; A[This is a () in text];';
    expect(() => flow.parser.parse(str)).toThrowError("got 'PS'");
  });

  it('should throw error for strings and text at the same time', function () {
    const str = 'graph TD;A(this node has "string" and text)-->|this link has "string" and text|C;';

    expect(() => flow.parser.parse(str)).toThrowError("got 'STR'");
  });

  it('should throw error for escaping quotes in text state', function () {
    //prettier-ignore
    const str = 'graph TD; A[This is a \"()\" in text];'; //eslint-disable-line no-useless-escape

    expect(() => flow.parser.parse(str)).toThrowError("got 'STR'");
  });

  it('should throw error for nested quotation marks', function () {
    const str = 'graph TD; A["This is a "()" in text"];';

    expect(() => flow.parser.parse(str)).toThrowError("Expecting 'SQE'");
  });

  it('should throw error', function () {
    const str =