gantt
    title Multi-Team Project
    dateFormat YYYY-MM-DD
    section Team A
    Task A1          :a1, 2024-01-01, 10d
    Task A2          :a2, after a1, 10d
    section Team B
    Task B1          :b1, 2024-01-01, 15d
    Task B2          :b2, after b1, 5d
    section Team C
    Task C1          :c1, 2024-01-10, 10d
    Task C2          :c2, after c1, 10d