gantt
    title Task Status
    dateFormat YYYY-MM-DD
    section Completed
    Task 1           :done, 2024-01-01, 5d
    Task 2           :done, 2024-01-06, 5d
    section In Progress
    Task 3           :active, 2024-01-11, 5d
    section Planned
    Task 4           :2024-01-16, 5d
    Task 5           :2024-01-21, 5d